<a href="https://colab.research.google.com/github/tashkinovnet/Home-Task/blob/Hometask_2/Hometask_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Hometask №2

####1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [ ]:
import numpy as np
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


####2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [ ]:
import numpy as np
a = np.indices((8, 8)).sum(axis=0) % 2
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


####3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [ ]:
import numpy as np
a = np.where(np.arange(5).reshape(5, 1) - np.arange(5) > 0, np.arange(5).reshape(5, 1) - np.arange(5), 0)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [2 1 0 0 0]
 [3 2 1 0 0]
 [4 3 2 1 0]]


####4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.

In [ ]:
import numpy as np
a = np.random.rand(5, 5)
mean_values = np.mean(a, axis=1).reshape(-1, 1)
a_normalized = a - mean_values
print(a_normalized)

[[-0.12752108 -0.20157187  0.41997326 -0.14982151  0.05894121]
 [-0.4533948   0.30563055  0.03803775  0.08463549  0.025091  ]
 [ 0.30397776  0.15009161 -0.09905738 -0.43051661  0.07550462]
 [ 0.20944789 -0.01083894 -0.37492735 -0.0089416   0.18526   ]
 [ 0.02364917  0.21159311  0.17277613 -0.54848852  0.14047011]]


####5. Cоздайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.


In [ ]:
import numpy as np
result = (a := np.random.random((3, 10)))[np.arange(3), np.abs(a - 0.5).argmin(axis=1)]
print(a)
print(result)

[[0.99937546 0.12670722 0.71910543 0.62282417 0.99761815 0.68475952
  0.90747426 0.65338047 0.10428337 0.69430616]
 [0.07354205 0.07653821 0.38697121 0.12638059 0.39350582 0.63969677
  0.78622665 0.03017186 0.8925646  0.59769962]
 [0.45666886 0.07214645 0.92184297 0.10334788 0.90842319 0.66033885
  0.15636644 0.12833492 0.82217921 0.00955165]]
[0.62282417 0.59769962 0.45666886]


####6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [ ]:
import numpy as np
a = 1000 * np.random.random((6, 6))
s = np.sum(a, axis=1)
b = np.max(a, axis=0)
result = s / b
print("Исходный:\n", a)
print("Результат:\n", result)


Исходный:
 [[404.34671295 528.77179775 199.73738868 400.04501772 903.87642638
  656.27973155]
 [677.27693084 677.85631054 725.92656255  72.37399673 196.84576788
  846.51733743]
 [996.82350175  69.37219805 922.91517399 815.69783666 221.81304555
  387.52007979]
 [376.90753012 922.55814517 151.64519042 559.01045907 245.88269853
  761.81806168]
 [321.32541989 249.28303983 764.55581305   8.50649099 636.2178017
  302.47524911]
 [779.72178843  15.69337042   1.7144445  546.95972102 833.51289106
  648.40693854]]
Результат:
 [3.10291347 3.46514409 3.69930188 3.69968136 2.5250839  3.33839489]


####7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [ ]:
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
maximum = np.max(x[1:][np.where(x[:-1] == 0)])
print(maximum)


5


####8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [ ]:
import numpy as np
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x += np.bincount(i, minlength = len(x))
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
